import { Workspace, day } from './models';
export function sampleWorkspace(): Workspace {
  const [p1, p2, p3, m1, m2, m3, s1] = Array.from({ length: 7 }, () => crypto.randomUUID());
  return {
    projects: [
      {
        id: p1,
        key: 'ORB',
        name: 'Portal de clientes',
        description: 'Acceso, seguimiento y comunicación en un solo lugar.',
        owner: m1,
        status: 'Activo',
      },
      {
        id: p2,
        key: 'NVA',
        name: 'Nueva plataforma',
        description: 'Evolución del producto y preparación del siguiente lanzamiento.',
        owner: m2,
        status: 'Activo',
      },
      {
        id: p3,
        key: 'OPS',
        name: 'Operaciones internas',
        description: 'Mejoras del flujo diario y documentación del equipo.',
        owner: m3,
        status: 'Activo',
      },
    ],
    members: [
      { id: m1, name: 'Ana Morales', role: 'Administradora', email: 'ana@ejemplo.com' },
      { id: m2, name: 'Diego Ruiz', role: 'Project Manager', email: 'diego@ejemplo.com' },
      { id: m3, name: 'Lucía Torres', role: 'Miembro', email: 'lucia@ejemplo.com' },
    ],
    sprints: [
      {
        id: s1,
        project_id: p2,
        name: 'Sprint de octubre',
        goal: 'Dejar listo el primer flujo de acceso',
        start: day(-5),
        end: day(9),
        status: 'Activo',
      },
    ],
    tickets: [
      {
        id: crypto.randomUUID(),
        key: 'ORB-101',
        project_id: p1,
        title: 'Revisar el flujo de registro',
        description: '',
        type: 'Tarea',
        status: 'En progreso',
        priority: 'Alta',
        assignee: m1,
        due: day(2),
        sprint_id: null,
      },
      {
        id: crypto.randomUUID(),
        key: 'NVA-102',
        project_id: p2,
        title: 'Diseñar la vista de bienvenida',
        description: '',
        type: 'Mejora',
        status: 'En revisión',
        priority: 'Media',
        assignee: m2,
        due: day(4),
        sprint_id: s1,
      },
      {
        id: crypto.randomUUID(),
        key: 'OPS-103',
        project_id: p3,
        title: 'Actualizar la guía de incorporación',
        description: '',
        type: 'Tarea',
        status: 'Pendiente',
        priority: 'Baja',
        assignee: m3,
        due: day(7),
        sprint_id: null,
      },
      {
        id: crypto.randomUUID(),
        key: 'NVA-104',
        project_id: p2,
        title: 'Resolver error de acceso móvil',
        description: '',
        type: 'Bug',
        status: 'Bloqueado',
        priority: 'Urgente',
        assignee: m1,
        due: day(1),
        sprint_id: s1,
      },
      {
        id: crypto.randomUUID(),
        key: 'ORB-105',
        project_id: p1,
        title: 'Ajustar mensajes de confirmación',
        description: '',
        type: 'Mejora',
        status: 'Completado',
        priority: 'Media',
        assignee: m3,
        due: day(-2),
        sprint_id: null,
      },
      {
        id: crypto.randomUUID(),
        key: 'NVA-106',
        project_id: p2,
        title: 'Preparar pruebas de navegación',
        description: '',
        type: 'Tarea',
        status: 'Pendiente',
        priority: 'Media',
        assignee: m2,
        due: day(10),
        sprint_id: s1,
      },
    ],
    notifications: [
      {
        id: crypto.randomUUID(),
        title: 'Bienvenido a Projectly',
        body: 'Tu espacio de demostración está listo. Explora los proyectos y organiza tu trabajo.',
        read: false,
        created_at: new Date().toISOString(),
      },
    ],
  };
}
